defmodule LokaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :loka

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_loka_key",
    signing_salt: "FV/yNqRN",
    same_site: "Lax"
  ]

  # Browser tests pass the Ecto sandbox owner in the user agent
  if Application.compile_env(:loka, :sql_sandbox) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:user_agent, session: @session_options]],
    longpoll: [connect_info: [:user_agent, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :loka,
    gzip: not code_reloading?,
    only: LokaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User uploads, directory resolved at runtime (see Loka.Uploads)
  plug Plug.Static,
    at: "/uploads",
    from: {Loka.Uploads, :dir, []}

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :loka
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug LokaWeb.Router
end
