defmodule Loka.Repo.Migrations.AddAdminFlagToUesr do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :admin?, :boolean
    end
  end

  def down do
    alter table(:users) do
      remove :admin?
    end
  end
end
