defmodule Loka.Repo.Migrations.AddStudioDescriptionAndLogo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:studios) do
      add :description, :text
      add :logo_path, :text
    end
  end

  def down do
    alter table(:studios) do
      remove :logo_path
      remove :description
    end
  end
end
