defmodule Loka.Repo.Migrations.AddOrderAndOrderLines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "orders_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:order_lines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :unit_price, :money_with_currency, null: false
      add :quantity, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_lines_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :stock_id,
          references(:stock,
            column: :id,
            name: "order_lines_stock_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:order_lines, "order_lines_order_id_fkey")

    drop constraint(:order_lines, "order_lines_stock_id_fkey")

    drop table(:order_lines)

    drop constraint(:orders, "orders_user_id_fkey")

    drop table(:orders)
  end
end
