defmodule Loka.Repo.Migrations.AddPriceToStockAndUniqueIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock) do
      add :price, :money_with_currency, null: false
    end

    create unique_index(:stock, [:item_id, :studio_id],
             name: "stock_unique_item_per_studio_index"
           )

    alter table(:items) do
      remove :price
    end
  end

  def down do
    alter table(:items) do
      add :price, :money_with_currency, null: false
    end

    drop_if_exists unique_index(:stock, [:item_id, :studio_id],
                     name: "stock_unique_item_per_studio_index"
                   )

    alter table(:stock) do
      remove :price
    end
  end
end
