defmodule Loka.Repo.Migrations.UniqueStudioOwner do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:studios, [:owner_id], name: "studios_unique_owner_index")
  end

  def down do
    drop_if_exists unique_index(:studios, [:owner_id], name: "studios_unique_owner_index")
  end
end
