defmodule Loka.Repo.Migrations.GenerateVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:items_versions, "items_versions_version_source_id_fkey")

    alter table(:items_versions) do
      modify :version_source_id,
             references(:items,
               column: :id,
               name: "items_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:items_versions, "items_versions_version_source_id_fkey")

    alter table(:items_versions) do
      modify :version_source_id,
             references(:items,
               column: :uuid_v7,
               name: "items_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
