defmodule Loka.Repo.Migrations.RequireStudioCity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "UPDATE studios SET city = '' WHERE city IS NULL"

    alter table(:studios) do
      modify :city, :text, null: false
    end
  end

  def down do
    alter table(:studios) do
      modify :city, :text, null: true
    end
  end
end
