defmodule Loka.Repo.Migrations.FixId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:items), :uuid_v7, to: :id

    alter table(:items) do
      modify :id, :uuid, default: fragment("uuid_generate_v7()")
    end
  end

  def down do
    alter table(:items) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    rename table(:items), :id, to: :uuid_v7
  end
end
