defmodule Loka.Repo.Migrations.ChangeStudioOwnerRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :studio_id
    end

    alter table(:studios) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "studios_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:studios, "studios_owner_id_fkey")

    alter table(:studios) do
      remove :owner_id
    end

    alter table(:users) do
      add :studio_id,
          references(:studios,
            column: :id,
            name: "users_studio_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
