defmodule Loka.Repo.Migrations.AddStudioCoordinates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:studios) do
      add :latitude, :float
      add :longitude, :float
    end
  end

  def down do
    alter table(:studios) do
      remove :longitude
      remove :latitude
    end
  end
end
