defmodule Loka.Repo.Migrations.EnableExtensions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("items", "items_pkey")

    create table(:items_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:items) do
      remove :id
      add :uuid_v7, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:items_versions) do
      modify :version_source_id,
             references(:items,
               column: :uuid_v7,
               name: "items_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:items) do
      add :archived_at, :utc_datetime_usec
    end
  end

  def down do
    drop constraint("items", "items_pkey")

    alter table(:items) do
      remove :archived_at
    end

    drop constraint(:items_versions, "items_versions_version_source_id_fkey")

    alter table(:items_versions) do
      modify :version_source_id, :uuid
    end

    alter table(:items) do
      remove :uuid_v7
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    drop table(:items_versions)
  end
end
