defmodule Loka.Repo.Migrations.Cart do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cart_stock) do
      modify :cart_id, :uuid, null: false
      modify :stock_id, :uuid, null: false
    end

    alter table(:cart) do
      modify :user_id, :uuid, null: false
    end
  end

  def down do
    alter table(:cart) do
      modify :user_id, :uuid, null: true
    end

    alter table(:cart_stock) do
      modify :stock_id, :uuid, null: true
      modify :cart_id, :uuid, null: true
    end
  end
end
