defmodule Loka.Repo.Migrations.AddStock do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stock_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:stock, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:stock_versions) do
      modify :version_source_id,
             references(:stock,
               column: :id,
               name: "stock_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:stock) do
      add :quantity, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :archived_at, :utc_datetime_usec

      add :item_id,
          references(:items,
            column: :id,
            name: "stock_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :studio_id,
          references(:studios,
            column: :id,
            name: "stock_studio_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:stock, "stock_item_id_fkey")

    drop constraint(:stock, "stock_studio_id_fkey")

    alter table(:stock) do
      remove :studio_id
      remove :item_id
      remove :archived_at
      remove :updated_at
      remove :inserted_at
      remove :quantity
    end

    drop constraint(:stock_versions, "stock_versions_version_source_id_fkey")

    alter table(:stock_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:stock)

    drop table(:stock_versions)
  end
end
