defmodule Loka.Repo.Migrations.AnonymousCart do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:cart_stock, "cart_stock_cart_id_fkey")

    alter table(:cart_stock) do
      modify :cart_id,
             references(:cart,
               column: :id,
               name: "cart_stock_cart_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:cart) do
      modify :user_id, :uuid, null: true
    end
  end

  def down do
    alter table(:cart) do
      modify :user_id, :uuid, null: false
    end

    drop constraint(:cart_stock, "cart_stock_cart_id_fkey")

    alter table(:cart_stock) do
      modify :cart_id,
             references(:cart,
               column: :id,
               name: "cart_stock_cart_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
