defmodule Loka.Repo.Migrations.AdminFlagNotNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # The column was added without a default, so existing rows are NULL and
    # would violate the NOT NULL constraint below.
    execute "UPDATE users SET \"admin?\" = false WHERE \"admin?\" IS NULL"

    alter table(:users) do
      modify :admin?, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      modify :admin?, :boolean, null: true, default: nil
    end
  end
end
