defmodule Loka.Repo.Migrations.RequireStudioPostalCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "UPDATE studios SET postal_code = '0000' WHERE postal_code IS NULL"

    alter table(:studios) do
      modify :postal_code, :text, null: false
    end
  end

  def down do
    alter table(:studios) do
      modify :postal_code, :text, null: true
    end
  end
end
