defmodule Loka.Repo.Migrations.StockFix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cart_stock, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :stock_id,
          references(:stock,
            column: :id,
            name: "cart_stock_stock_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :cart_id,
          references(:cart,
            column: :id,
            name: "cart_stock_cart_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:cart_stock, "cart_stock_stock_id_fkey")

    drop constraint(:cart_stock, "cart_stock_cart_id_fkey")

    drop table(:cart_stock)
  end
end
