defmodule Loka.Repo.Migrations.AddStudioAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:studios) do
      add :street, :text
      add :house_number, :text
      add :city, :text
      add :postal_code, :text
    end
  end

  def down do
    alter table(:studios) do
      remove :postal_code
      remove :city
      remove :house_number
      remove :street
    end
  end
end
